fontname: savage
familyname: savage-icons
formats:
  - svg
  - oft
  - woff
  - ttf
  - eot

glyphwidth: 1024
em: 1000
encoding: 'utf-8'
defaultRangeStart: 127744
classprefix: svg-
classname: 'savage'
